spring:
  application:
    name: service-discovery
  profiles:
    active: home
  output:
    ansi:
      enabled: ALWAYS

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    web: error
