spring:
  application:
    name: service-discovery
  profiles:
    active: home
  output:
    ansi:
      enabled: ALWAYS
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
logging:
  level:
    web: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"